### ISSUE TITLE
Rename NewSErr to Parse

### ISSUE THREAD

**Issue by dolmen** [robaho/fixed#15]
Rename `NewSErr` to `Parse`, `NewS` to `MustParse` to follow stdlib style (see package `text/template`).

**Comment by robaho** [comment]
Did you maybe mean a different package? I don’t see a MustParse, and the Parse returns an error?

**Comment by dolmen** [comment]
Well, `text/template` has [`func Must`](https://golang.org/pkg/text/template/#Must) that can be used to wrap `Parse`.
The `text/template` test suite also has a [`mustParse` func](https://golang.org/src/html/template/template_test.go?h=mustParse#L134).

**Comment by robaho** [comment]
yea both of those panic on failure, which is what I would expect "must" to mean, and I don't think we would want that in a math lib - although in other languages they would definitely throw an exception - not Go though

**Comment by dolmen** [comment]
So you think that just silently ignoring parse errors (like in [the current implementation of `NewS`](https://github.com/robaho/fixed/blob/8e216f0c4d76069ef5f98bbfbf47fadc6d148142/fixed.go#L35)) is just better than a panic?

**Comment by robaho** [comment]
No, the value will be NaN in this case which propagates. Using NewS is typically for constants in chained math operations. There is NewSErr for dynamic Fixed creation. Two different use cases.

**Comment by robaho** [comment]
As an example, when you write

b = a + 5

There is no error checking that 5 is the correct value to be used. That this code is correct is varied elsewhere. 

Similarly, if I mistakenly write

b = a.Add(NewS(“x”))

b will have the value of NaN which needs to be verified elsewhere.

**Comment by dolmen** [comment]
My point is that if I mistakenly write `NewS("x")` my program should fail early (panic), instead of me having to debug deeply to find the hidden source of that `NaN`.

**Comment by robaho** [comment]
Then use NewSErr, check the err and panic. 

Like I said, NewS is designed for typed constants. No difference in mistakingly typing 6 when you meant to type 5. 

NewSErr is for parsing external inputs where a possible format error is far, far, greater.

**Comment by robaho** [comment]
Added Parse and MustParae
