### ISSUE TITLE
protobuf friendly

### ISSUE THREAD

**Issue by k1ng440** [robaho/fixed#16]
it would be awesome if we can use it with Protobuf.

**Comment by robaho** [comment]
I’ll look into it. The go-trader uses doubles in grpc - which is not really correct - for ease of development at the time. So it would be a worthwhile change.

**Comment by robaho** [comment]
A big problem is the protobufs is cross platform, so the only reasonable way would be to encode as strings, but have the Go Marshall to/from fixed.

**Comment by k1ng440** [comment]
please check this protobuf 

https://github.com/googleapis/googleapis/blob/master/google/type/money.proto

**Comment by robaho** [comment]
Which would also then require exposing read and write access to the internal long. But it would be better than encoding as string since it would be more efficient.

**Comment by k1ng440** [comment]
please read this helper library for timestamp https://github.com/golang/protobuf/blob/master/ptypes/timestamp.go

**Comment by robaho** [comment]
@k1ng440  I understand, but if you notice Timestamp is an approved 'known type' by the protobufs project and that is why it is directly (and easily) supported.

protobufs would need to declare a "fixed place" decimal to allow fixed.Fixed to work as easily.

**Comment by robaho** [comment]
closing this as infeasible
