### ISSUE TITLE
can fixed handle this 0.0002849002849002849?

### ISSUE THREAD

**Issue by k1ng440** [robaho/fixed#17]
Hello,
can fixed handle decimal points like this 0.0002849002849002849 with 100% precision?

**Comment by robaho** [comment]
No. The current code has a max of 7 decimal places. It can be changed in a vendor copy to any number of decimal places, but the total digit count must be < 18 (the number of digits in 63 bits).

You most likely want to use big.Decimal or third-part decimal.Decimal.

This library is for performance when the use case fits the above restriction.
