### ISSUE TITLE
Question regarding rounding implementation

### ISSUE THREAD

**Issue by lightsgoout** [robaho/fixed#24]
I'm rewriting some code from python to go and using this excellent library.

As I understand this library implements rounding using `ROUND_HALF_UP` algorithm, but I've noticed that sometimes this library rounds numbers differently from python's decimal package, see example:

```go
fmt.Printf("%s\n", fixed.MustParse("2234.565").Round(2).String()) // 2234.56
```

```python3
print(decimal.Decimal("2234.565").quantize(decimal.Decimal("0.01"), rounding=decimal.ROUND_HALF_UP)) # 2234.57
```

So, for input `2234.565` fixed's output is `2234.56`, while python's output is `2234.57`.

Is `.56` result correct? I think rounding away from zero should give us `.57`.

Also could you please clarify that `ROUND_HALF_UP` from python should match this library's version? Or maybe I'm wrong and should be comparing this library to some other python rounding mode (https://docs.python.org/3/library/decimal.html#rounding-modes). I assume I should be comparing against `ROUND_HALF_UP` because fixed's source code says so:

```go
// Round returns a rounded (half-up, away from zero) to n decimal places
func (f Fixed) Round(n int) Fixed {
```

**Comment by robaho** [comment]
There was an issue with floating point error. I posted a fix.

**Comment by lightsgoout** [comment]
Awesome! Thanks.
